/* Ultiway.h generated by valac 0.30.0, the Vala compiler, do not modify */


#ifndef __ULTIWAY_H__
#define __ULTIWAY_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS


#define ULTI_TYPE_ULTI_LAUNCH (ulti_ulti_launch_get_type ())
#define ULTI_ULTI_LAUNCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ULTI_TYPE_ULTI_LAUNCH, UltiUltiLaunch))
#define ULTI_ULTI_LAUNCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ULTI_TYPE_ULTI_LAUNCH, UltiUltiLaunchClass))
#define ULTI_IS_ULTI_LAUNCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ULTI_TYPE_ULTI_LAUNCH))
#define ULTI_IS_ULTI_LAUNCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ULTI_TYPE_ULTI_LAUNCH))
#define ULTI_ULTI_LAUNCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ULTI_TYPE_ULTI_LAUNCH, UltiUltiLaunchClass))

typedef struct _UltiUltiLaunch UltiUltiLaunch;
typedef struct _UltiUltiLaunchClass UltiUltiLaunchClass;
typedef struct _UltiUltiLaunchPrivate UltiUltiLaunchPrivate;

#define ULTI_TYPE_ACTION_MENU (ulti_action_menu_get_type ())
#define ULTI_ACTION_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ULTI_TYPE_ACTION_MENU, UltiActionMenu))
#define ULTI_ACTION_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ULTI_TYPE_ACTION_MENU, UltiActionMenuClass))
#define ULTI_IS_ACTION_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ULTI_TYPE_ACTION_MENU))
#define ULTI_IS_ACTION_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ULTI_TYPE_ACTION_MENU))
#define ULTI_ACTION_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ULTI_TYPE_ACTION_MENU, UltiActionMenuClass))

typedef struct _UltiActionMenu UltiActionMenu;
typedef struct _UltiActionMenuClass UltiActionMenuClass;
typedef struct _UltiActionMenuPrivate UltiActionMenuPrivate;

#define ULTI_TYPE_ULTIPOST (ulti_ultipost_get_type ())
#define ULTI_ULTIPOST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ULTI_TYPE_ULTIPOST, UltiUltipost))
#define ULTI_ULTIPOST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ULTI_TYPE_ULTIPOST, UltiUltipostClass))
#define ULTI_IS_ULTIPOST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ULTI_TYPE_ULTIPOST))
#define ULTI_IS_ULTIPOST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ULTI_TYPE_ULTIPOST))
#define ULTI_ULTIPOST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ULTI_TYPE_ULTIPOST, UltiUltipostClass))

typedef struct _UltiUltipost UltiUltipost;
typedef struct _UltiUltipostClass UltiUltipostClass;
typedef struct _UltiUltipostPrivate UltiUltipostPrivate;

#define ULTI_TYPE_ULTI_PANEL (ulti_ulti_panel_get_type ())
#define ULTI_ULTI_PANEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ULTI_TYPE_ULTI_PANEL, UltiUltiPanel))
#define ULTI_ULTI_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ULTI_TYPE_ULTI_PANEL, UltiUltiPanelClass))
#define ULTI_IS_ULTI_PANEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ULTI_TYPE_ULTI_PANEL))
#define ULTI_IS_ULTI_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ULTI_TYPE_ULTI_PANEL))
#define ULTI_ULTI_PANEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ULTI_TYPE_ULTI_PANEL, UltiUltiPanelClass))

typedef struct _UltiUltiPanel UltiUltiPanel;
typedef struct _UltiUltiPanelClass UltiUltiPanelClass;
typedef struct _UltiUltiPanelPrivate UltiUltiPanelPrivate;

struct _UltiUltiLaunch {
	GtkWindow parent_instance;
	UltiUltiLaunchPrivate * priv;
};

struct _UltiUltiLaunchClass {
	GtkWindowClass parent_class;
};

struct _UltiActionMenu {
	GtkWindow parent_instance;
	UltiActionMenuPrivate * priv;
};

struct _UltiActionMenuClass {
	GtkWindowClass parent_class;
};

struct _UltiUltipost {
	GtkBin parent_instance;
	UltiUltipostPrivate * priv;
	GtkToggleButton* Launch;
	GtkToggleButton* Action;
	UltiUltiPanel* p;
	UltiActionMenu* action;
};

struct _UltiUltipostClass {
	GtkBinClass parent_class;
};

struct _UltiUltiPanel {
	GtkBin parent_instance;
	UltiUltiPanelPrivate * priv;
	gboolean has_activated;
};

struct _UltiUltiPanelClass {
	GtkBinClass parent_class;
};


GType ulti_ulti_launch_get_type (void) G_GNUC_CONST;
void ulti_ulti_launch_vanish (UltiUltiLaunch* self);
void ulti_ulti_launch_appear (UltiUltiLaunch* self);
UltiUltiLaunch* ulti_ulti_launch_new (void);
UltiUltiLaunch* ulti_ulti_launch_construct (GType object_type);
GType ulti_action_menu_get_type (void) G_GNUC_CONST;
void ulti_action_menu_appear (UltiActionMenu* self);
void ulti_action_menu_vanish (UltiActionMenu* self);
UltiActionMenu* ulti_action_menu_new (void);
UltiActionMenu* ulti_action_menu_construct (GType object_type);
GType ulti_ultipost_get_type (void) G_GNUC_CONST;
GType ulti_ulti_panel_get_type (void) G_GNUC_CONST;
UltiUltipost* ulti_ultipost_new (GtkWidget* BtnTask, UltiUltiPanel* panel);
UltiUltipost* ulti_ultipost_construct (GType object_type, GtkWidget* BtnTask, UltiUltiPanel* panel);
extern UltiUltipost* ulti_ulti_panel_post;
extern UltiUltiLaunch* ulti_ulti_panel_launcher;
UltiUltiPanel* ulti_ulti_panel_new (GtkWidget* btn);
UltiUltiPanel* ulti_ulti_panel_construct (GType object_type, GtkWidget* btn);


G_END_DECLS

#endif
